load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "wheelos_msgs_python_init",
    srcs = glob(["**/__init__.py"]),
)

cc_library(
    name = "wheelos_msgs_cc_proto",
    deps = [
        ":audio_msgs_cc_proto",
        ":basic_msgs_cc_proto",
        ":chassis_msgs_cc_proto",
        ":config_msgs_cc_proto",
        ":control_msgs_cc_proto",
        ":dreamview_msgs_cc_proto",
        ":drivers_msgs_cc_proto",
        ":guardian_msgs_cc_proto",
        ":localization_msgs_cc_proto",
        ":map_msgs_cc_proto",
        ":mission_msgs_cc_proto",
        ":monitor_msgs_cc_proto",
        ":perception_msgs_cc_proto",
        ":planning_msgs_cc_proto",
        ":prediction_msgs_cc_proto",
        ":routing_msgs_cc_proto",
        ":sensor_msgs_cc_proto",
        ":simulation_msgs_cc_proto",
        ":storytelling_msgs_cc_proto",
        ":transform_msgs_cc_proto",
        ":v2x_msgs_cc_proto",
    ],
)

alias(
    name = "audio_msgs_cc_proto",
    actual = "//wheelos_msgs/audio_msgs:audio_msgs_cc_proto",
)

alias(
    name = "audio_msgs_py",
    actual = "//wheelos_msgs/audio_msgs:audio_msgs_py",
)

alias(
    name = "basic_msgs_cc_proto",
    actual = "//wheelos_msgs/basic_msgs:basic_msgs_cc_proto",
)

alias(
    name = "basic_msgs_py",
    actual = "//wheelos_msgs/basic_msgs:basic_msgs_py",
)

alias(
    name = "chassis_msgs_cc_proto",
    actual = "//wheelos_msgs/chassis_msgs:chassis_msgs_cc_proto",
)

alias(
    name = "chassis_msgs_py",
    actual = "//wheelos_msgs/chassis_msgs:chassis_msgs_py",
)

alias(
    name = "config_msgs_cc_proto",
    actual = "//wheelos_msgs/config_msgs:config_msgs_cc_proto",
)

alias(
    name = "config_msgs_py",
    actual = "//wheelos_msgs/config_msgs:config_msgs_py",
)

alias(
    name = "control_msgs_cc_proto",
    actual = "//wheelos_msgs/control_msgs:control_msgs_cc_proto",
)

alias(
    name = "control_msgs_py",
    actual = "//wheelos_msgs/control_msgs:control_msgs_py",
)

alias(
    name = "dreamview_msgs_cc_proto",
    actual = "//wheelos_msgs/dreamview_msgs:dreamview_msgs_cc_proto",
)

alias(
    name = "dreamview_msgs_py",
    actual = "//wheelos_msgs/dreamview_msgs:dreamview_msgs_py",
)

alias(
    name = "drivers_msgs_cc_proto",
    actual = "//wheelos_msgs/drivers_msgs:drivers_msgs_cc_proto",
)

alias(
    name = "drivers_msgs_py",
    actual = "//wheelos_msgs/drivers_msgs:drivers_msgs_py",
)

alias(
    name = "guardian_msgs_cc_proto",
    actual = "//wheelos_msgs/guardian_msgs:guardian_msgs_cc_proto",
)

alias(
    name = "guardian_msgs_py",
    actual = "//wheelos_msgs/guardian_msgs:guardian_msgs_py",
)

alias(
    name = "localization_msgs_cc_proto",
    actual = "//wheelos_msgs/localization_msgs:localization_msgs_cc_proto",
)

alias(
    name = "localization_msgs_py",
    actual = "//wheelos_msgs/localization_msgs:localization_msgs_py",
)

alias(
    name = "map_msgs_cc_proto",
    actual = "//wheelos_msgs/map_msgs:map_msgs_cc_proto",
)

alias(
    name = "map_msgs_py",
    actual = "//wheelos_msgs/map_msgs:map_msgs_py",
)

alias(
    name = "mission_msgs_cc_proto",
    actual = "//wheelos_msgs/mission_msgs:mission_msgs_cc_proto",
)

alias(
    name = "mission_msgs_py",
    actual = "//wheelos_msgs/mission_msgs:mission_msgs_py",
)

alias(
    name = "monitor_msgs_cc_proto",
    actual = "//wheelos_msgs/monitor_msgs:monitor_msgs_cc_proto",
)

alias(
    name = "monitor_msgs_py",
    actual = "//wheelos_msgs/monitor_msgs:monitor_msgs_py",
)

alias(
    name = "perception_msgs_cc_proto",
    actual = "//wheelos_msgs/perception_msgs:perception_msgs_cc_proto",
)

alias(
    name = "perception_msgs_py",
    actual = "//wheelos_msgs/perception_msgs:perception_msgs_py",
)

alias(
    name = "planning_msgs_cc_proto",
    actual = "//wheelos_msgs/planning_msgs:planning_msgs_cc_proto",
)

alias(
    name = "planning_msgs_py",
    actual = "//wheelos_msgs/planning_msgs:planning_msgs_py",
)

alias(
    name = "prediction_msgs_cc_proto",
    actual = "//wheelos_msgs/prediction_msgs:prediction_msgs_cc_proto",
)

alias(
    name = "prediction_msgs_py",
    actual = "//wheelos_msgs/prediction_msgs:prediction_msgs_py",
)

alias(
    name = "routing_msgs_cc_proto",
    actual = "//wheelos_msgs/routing_msgs:routing_msgs_cc_proto",
)

alias(
    name = "routing_msgs_py",
    actual = "//wheelos_msgs/routing_msgs:routing_msgs_py",
)

alias(
    name = "sensor_msgs_cc_proto",
    actual = "//wheelos_msgs/sensor_msgs:sensor_msgs_cc_proto",
)

alias(
    name = "sensor_msgs_py",
    actual = "//wheelos_msgs/sensor_msgs:sensor_msgs_py",
)

alias(
    name = "simulation_msgs_cc_proto",
    actual = "//wheelos_msgs/simulation_msgs:simulation_msgs_cc_proto",
)

alias(
    name = "simulation_msgs_py",
    actual = "//wheelos_msgs/simulation_msgs:simulation_msgs_py",
)

alias(
    name = "storytelling_msgs_cc_proto",
    actual = "//wheelos_msgs/storytelling_msgs:storytelling_msgs_cc_proto",
)

alias(
    name = "storytelling_msgs_py",
    actual = "//wheelos_msgs/storytelling_msgs:storytelling_msgs_py",
)

alias(
    name = "transform_msgs_cc_proto",
    actual = "//wheelos_msgs/transform_msgs:transform_msgs_cc_proto",
)

alias(
    name = "transform_msgs_py",
    actual = "//wheelos_msgs/transform_msgs:transform_msgs_py",
)

alias(
    name = "v2x_msgs_cc_proto",
    actual = "//wheelos_msgs/v2x_msgs:v2x_msgs_cc_proto",
)

alias(
    name = "v2x_msgs_py",
    actual = "//wheelos_msgs/v2x_msgs:v2x_msgs_py",
)

py_library(
    name = "wheelos_msgs_py",
    deps = [
        "//wheelos_msgs:wheelos_msgs_python_init",
        ":audio_msgs_py",
        ":basic_msgs_py",
        ":chassis_msgs_py",
        ":config_msgs_py",
        ":control_msgs_py",
        ":dreamview_msgs_py",
        ":drivers_msgs_py",
        ":guardian_msgs_py",
        ":localization_msgs_py",
        ":map_msgs_py",
        ":mission_msgs_py",
        ":monitor_msgs_py",
        ":perception_msgs_py",
        ":planning_msgs_py",
        ":prediction_msgs_py",
        ":routing_msgs_py",
        ":sensor_msgs_py",
        ":simulation_msgs_py",
        ":storytelling_msgs_py",
        ":transform_msgs_py",
        ":v2x_msgs_py",
    ],
)
